# Generated by Django 5.1.3 on 2024-12-02 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0002_alter_coordinator_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='coordinators', to='coordination.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
